#student management  system
from tkinter import *
from tkinter import messagebox,ttk
from PIL import Image,ImageTk
import mysql.connector as sql
mycon=sql.connect(host="localhost",user="root",password="root",database="IGNTU_RCM")
mycur=mycon.cursor()
win=Tk()              
win.geometry('500x500')
win.resizable(0,0)
win.title("IGNTU")
win.iconbitmap("C:\\Users\\rk751\\Downloads\\logo.ico")
win.config(background="blue")
cb=IntVar()
name=StringVar()
email_id=StringVar()
password=StringVar()
sid=StringVar()
mob_no=StringVar()
course=StringVar()
def cbs():
    if cb.get()==1:
        b1['state']=ACTIVE
    else :
        b1['state']=DISABLED
def signup():
    win1=Toplevel(win)
    win1.title("new account")
    win1.geometry("600x400")
    win1.resizable(0,0)
    win1.iconbitmap("C:\\Users\\rk751\\Downloads\\logo.ico")
    win1.config(background="lightgreen")
    l4=Label(win1,text="Create new account",bg="lightgreen",fg="black",font=('algerian',16,'bold'),bd=5)
    l4.place(x=100,y=20)
    l1=Label(win1,text="Name :",bg="lightgreen",fg="black",font=('algerian',16,'bold'),bd=5)
    l1.place(x=20,y=90)
    e1=Entry(win1,font=("algerian",16,"bold"),bg="white",fg="black",bd=5,width=25,textvariable=name)
    e1.place(x=170,y=90)
    l2=Label(win1,text="Email_id:",bg="lightgreen",fg="black",font=('algerian',16,'bold'),bd=5)
    l2.place(x=20,y=140)
    e2=Entry(win1,font=("algerian",16,"bold"),bg="white",fg="black",bd=5,width=25,textvariable=email_id)
    e2.place(x=170,y=140)
    l3=Label(win1,text="Password:",bg="lightgreen",fg="black",font=('algerian',16,'bold'),bd=5)
    l3.place(x=20,y=190)
    e3=Entry(win1,font=("algerian",16,"bold"),bg="white",fg="black",bd=5,width=25,show="*",textvariable=password)
    e3.place(x=170,y=190)
    def submit():
        n=name.get()
        e=email_id.get()
        p=password.get()
        if n=="" or e=="" or p=="" :
            messagebox.showinfo("error","all fiels are required")
        else:
            q="insert into login values('{}','{}','{}')".format(n,e,p)
            mycur.execute(q)
            mycon.commit()
            messagebox.showinfo("saved","record save succesfully")
    b1=Button(win1,text="Submit",font=("algerian",10),bg="green",fg="white",bd=5,command=submit)
    b1.place(x=70,y=270)
def signin():
    em=email_id.get()
    pa=password.get()
    q="select * from login where email_id ='{}' and password ='{}' ".format(em,pa)
    mycur.execute(q)
    rec=mycur.fetchone()
    if rec==None or em=="" or pa=="":
         messagebox.showinfo("not match","emailid or password invalid")
    else :
        messagebox.showinfo("Record match","signin successfully")
        win1=Toplevel(win)
        win1.geometry("500x500")
        win1.resizable(0,0)
        win.iconbitmap("C:\\Users\\rk751\\Downloads\\logo.ico")
        win1.config(background="lightgreen")
        l1=Label(win1,text="IGNTU_RCM student management",bg="lightgreen",fg="black",font=('algerian',18,"bold"),bd=5)
        l1.pack(padx=0,pady=5)
        def admission():
            win=Toplevel(win1)
            win.title("admission")
            win.geometry("500x500")
            win.resizable(0,0)
            win.iconbitmap("C:\\Users\\rk751\\Downloads\\logo.ico")
            win.config(background="lightgreen")
            l1=Label(win,text="IGNTU_RCM student management",bg="lightgreen",fg="black",font=('algerian',18,"bold"),bd=5)
            l1.pack(padx=0,pady=5)
            l2=Label(win,text="sid :",bg="lightgreen",fg="white",font=('algerian',16,'bold'),bd=5)
            l2.place(x=20,y=70)
            e1=Entry(win,font=("algerian",16,"bold"),bg="white",fg="black",bd=5,width=25,textvariable=sid)
            e1.place(x=140,y=70)
            l3=Label(win,text="Name :",bg="lightgreen",fg="white",font=('algerian',16,'bold'),bd=5)
            l3.place(x=20,y=120)
            e2=Entry(win,font=("algerian",16,"bold"),bg="white",fg="black",bd=5,width=25,textvariable=name)
            e2.place(x=140,y=120)
            l4=Label(win,text="mob_No :",bg="lightgreen",fg="white",font=('algerian',16,'bold'),bd=5)
            l4.place(x=20,y=170)
            e3=Entry(win,font=("algerian",16,"bold"),bg="white",fg="black",bd=5,width=25,textvariable=mob_no)
            e3.place(x=140,y=170)
            l5=Label(win,text="course",bg="lightgreen",fg="white",font=('algerian',16,'bold'),bd=5)
            l5.place(x=20,y=220)
            e4=Entry(win,font=("algerian",16,"bold"),bg="white",fg="black",bd=5,width=25,textvariable=course)
            e4.place(x=140,y=220)
            def savedata():
                sa=sid.get()
                sn=name.get()
                sm=mob_no.get()
                sc=course.get()
                q="insert into student values('{}','{}','{}','{}')".format(sa,sn,sm,sc)
                mycur.execute(q)
                if sa=="" or sn=="" or sm=="" or sc=="":
                    messagebox.showinfo("invalid","please all details must required")
                else:
                    mycon.commit()
                    messagebox.showinfo("Record saved","Record add successfully")
            b1=Button(win,text='Save',bg='green',fg='black',font=('algerian',14,'bold'),bd=5,command=savedata)
            b1.place(x=70,y=300)
            win.mainloop()
        def update():
            win=Toplevel(win1)
            win.title("update")
            win.geometry("500x500")
            win.resizable(0,0)
            win.iconbitmap("C:\\Users\\rk751\\Downloads\\logo.ico")
            win.config(background="lightgreen")
            l1=Label(win,text="updating",bg="lightgreen",fg="black",font=('algerian',18,"bold"),bd=5)
            l1.pack(padx=0,pady=5)
            l2=Label(win,text="sid :",bg="lightgreen",fg="black",font=('algerian',16,'bold'),bd=5)
            l2.place(x=20,y=70)
            e1=Entry(win,font=("algerian",16,"bold"),bg="white",fg="black",bd=5,width=25,textvariable=sid)
            e1.place(x=140,y=70)
            l3=Label(win,text="Name :",bg="lightgreen",fg="black",font=('algerian',16,'bold'),bd=5)
            l3.place(x=20,y=120)
            e2=Entry(win,font=("algerian",16,"bold"),bg="white",fg="black",bd=5,width=25,textvariable=name)
            e2.place(x=140,y=120)
            l4=Label(win,text="mob_No :",bg="lightgreen",fg="black",font=('algerian',16,'bold'),bd=5)
            l4.place(x=20,y=170)
            e3=Entry(win,font=("algerian",16,"bold"),bg="white",fg="black",bd=5,width=25,textvariable=mob_no)
            e3.place(x=140,y=170)
            l5=Label(win,text="course",bg="lightgreen",fg="black",font=('algerian',16,'bold'),bd=5)
            l5.place(x=20,y=220)
            e4=Entry(win,font=("algerian",16,"bold"),bg="white",fg="black",bd=5,width=25,textvariable=course)
            e4.place(x=140,y=220)
            def change():
                sa=sid.get()
                sn=name.get()
                sm=mob_no.get()
                sc=course.get()
                q="update student set name='{}',mob_no='{}',course='{}' where sid='{}' ".format(sn,sm,sc,sa)
                mycur.execute(q)
                if sa==None or sm=="" or sn=="" or sc=="":
                    messagebox.showinfo("invalid","please filled vaild details")
                else:
                    mycon.commit()
                    messagebox.showinfo("Record update","Record update successfully")
            b1=Button(win,text='Save',bg='green',fg='black',font=('algerian',14,'bold'),bd=5,command=change)
            b1.place(x=70,y=300)
            win.mainloop()
        def delete():
            win=Toplevel(win1)
            win.title("delete")
            win.geometry("500x500")
            win.resizable(0,0)
            win.iconbitmap("C:\\Users\\rk751\\Downloads\\logo.ico")
            win.config(background="lightgreen")
            l2=Label(win,text="sid :",bg="lightgreen",fg="black",font=('algerian',16,'bold'),bd=5)
            l2.place(x=20,y=70)
            e1=Entry(win,font=("algerian",16,"bold"),bg="white",fg="black",bd=5,width=25,textvariable=sid)
            e1.place(x=140,y=70)
            def deletedata():
                sa=sid.get()
                q="delete from student where sid='{}' ".format(sa)
                mycur.execute(q)
                if sa=="" or sa==None:
                    messagebox.showinfo("invalid","please valid details field")
                else:
                    mycon.commit()
                    messagebox.showinfo("Record delete","Record delete successfully")
            b1=Button(win,text='delete',bg='green',fg='black',font=('algerian',14,'bold'),bd=5,command=deletedata)
            b1.place(x=70,y=150)
            win.mainloop()
        def deletelogin():
            win2=Toplevel(win)
            win2.title("delete")
            win2.geometry("500x500")
            win2.resizable(0,0)
            win2.iconbitmap("C:\\Users\\rk751\\Downloads\\logo.ico")
            win2.config(background="lightgreen")
            l2=Label(win2,text="email_id :",bg="lightgreen",fg="black",font=('algerian',16,'bold'),bd=5)
            l2.place(x=20,y=70)
            e1=Entry(win2,font=("algerian",16,"bold"),bg="white",fg="black",bd=5,width=25,textvariable=email_id)
            e1.place(x=140,y=70)
            def deletdata():
                em=email_id.get()
                q="delete from login where email_id='{}' ".format(em)
                mycur.execute(q)
                if em=="" or em==None:
                    messagebox.showinfo("invalid","please valid details field")
                else:
                    mycon.commit()
                    messagebox.showinfo("Record delete","Record delete successfully")
            b1=Button(win2,text='delete',bg='green',fg='black',font=('algerian',14,'bold'),bd=5,command=deletdata)
            b1.place(x=70,y=150)
            win.mainloop()
        def singdetails():
            win=Toplevel(win1)
            win.title("logineDetails")
            win.geometry("600x300")
            win.resizable(0,0)
            win.iconbitmap("C:\\Users\\rk751\\Downloads\\logo.ico")
            win.config(background="lightgreen")
            q="select * from login"
            mycur.execute(q)
            tree=ttk.Treeview(win)
            # define number of columns
            tree["columns"]=("name","email_id","password")
            #assign the width,minwidth and anchor to the respective columns
            tree.column("name",width=100,minwidth=100,anchor=W)
            tree.column("email_id",width=150,minwidth=150,anchor=W)
            tree.column("password",width=100,minwidth=100,anchor=W)
            # assign the heading names to the respective columns
            tree.heading("name",text="name",anchor=W)
            tree.heading("email_id",text="email_id",anchor=W)
            tree.heading("password",text="password",anchor=W)
            i=0
            for ro in mycur:
                tree.insert("",i,text="",values=(ro[0],ro[1],ro[2]))
                i=i+1
            tree.pack()
            win.mainloop()
        def showdetails():
             win=Toplevel(win1)
             win.title("showDetails")
             win.geometry("700x400")
             win.resizable(0,0)
             win.iconbitmap("C:\\Users\\rk751\\Downloads\\logo.ico")
             win.config(background="lightgreen")
             q="select * from student"
             mycur.execute(q)
             tree=ttk.Treeview(win)
             # define number of columns
             tree["columns"]=("sid","name","mob_no","course")
             #assign the width,minwidth and anchor to the respective columns
             tree.column("sid",width=100,minwidth=100,anchor=W)
             tree.column("name",width=100,minwidth=100,anchor=W)
             tree.column("mob_no",width=100,minwidth=100,anchor=W)
             tree.column("course",width=150,minwidth=150,anchor=W)
             # assign the heading names to the respective columns
             tree.heading("sid",text="sid",anchor=W)
             tree.heading("name",text="name",anchor=W)
             tree.heading("mob_no",text="mob_no",anchor=W)
             tree.heading("course",text="course",anchor=W)
             i=0
             for ro in mycur:
                 tree.insert("",i,text="",values=(ro[0],ro[1],ro[2],ro[3]))
                 i=i+1
             tree.pack()
             win.mainloop()
        b2=Button(win1,text="New Admission",bg="green",fg="white",font=("algerian",14,"bold"),bd=4,command=admission)
        b2.place(x=300,y=130)
        b3=Button(win1,text="Update",bg="green",fg="white",font=("algerian",14,"bold"),bd=4,command=update)
        b3.place(x=300,y=180)
        b4=Button(win1,text="Delete student",bg="green",fg="white",font=("algerian",14,"bold"),bd=4,command=delete)
        b4.place(x=300,y=230)
        b5=Button(win1,text="Delete user",bg="green",fg="white",font=("algerian",14,"bold"),bd=4,command=deletelogin)
        b5.place(x=300,y=280)
        b6=Button(win1,text="User Details",bg="green",fg="white",font=("algerian",14,"bold"),bd=4,command=singdetails)
        b6.place(x=300,y=330)
        b7=Button(win1,text="student Details",bg="green",fg="white",font=("algerian",14,"bold"),bd=4,command=showdetails)
        b7.place(x=300,y=380)
        win1.mainloop()
def forgotpassword():
    win1=Toplevel(win)
    win1.geometry("400x400")
    win1.resizable(0,0)
    win1.iconbitmap("C:\\Users\\rk751\\Downloads\\logo.ico")
    win1.config(background="lightgreen")
    l1=Label(win1,text=" Email_Id :",bg="lightgreen",fg="black",font=('algerian',16,'bold'),bd=5)
    l1.place(x=60,y=70)
    e3=Entry(win1,font=("algerian",16,"bold"),bg="white",fg="black",bd=5,width=20,textvariable=email_id)
    e3.place(x=20,y=100)
    l2=Label(win1,text=" New Password :",bg="lightgreen",fg="black",font=('algerian',16,'bold'),bd=5)
    l2.place(x=60,y=170)
    e3=Entry(win1,font=("algerian",16,"bold"),bg="white",fg="black",bd=5,width=20,show="*",textvariable=password)
    e3.place(x=20,y=200)
    def newpassword():
        p=password.get()
        e=email_id.get()
        q="update login set password='{}' where email_id='{}'".format(p,e)
        mycur.execute(q)
        if e==None or e=="":
            messagebox.showinfo("invalid","invalid email_id")
        else:
            mycon.commit()
            messagebox.showinfo("save password","saved password successfully")
    b3=Button(win1,text="new password save",font=("algerian",10),bg="blue",fg="white",bd=5,command=newpassword)
    b3.place(x=70,y=250)
    win.mainloop()
l1=Label(win,text="IGNTU_RCM Login System",bg="blue",fg="white",font=('algerian',18,"bold"),bd=5)
l1.pack(padx=0,pady=5)
image=Image.open("C:\\Users\\rk751\\OneDrive\\Desktop\\logo.png")
im=image.resize((50,50))
im=ImageTk.PhotoImage(im)
l7=Label(win,image=im)
l7.place(x=10,y=10)
image=Image.open("C:\\Users\\rk751\\OneDrive\\Documents\\user.png")
im1=image.resize((100,100))
im1=ImageTk.PhotoImage(im1)
l7=Label(win,image=im1)
l7.place(x=170,y=55)
l3=Label(win,text=" Email_Id",bg="blue",fg="white",font=('algerian',16,'bold'),bd=5)
l3.place(x=160,y=170)
e2=Entry(win,font=("algerian",16,"bold"),bg="white",fg="black",bd=5,width=25,textvariable=email_id)
e2.place(x=80,y=200)
l4=Label(win,text="Password",bg="blue",fg="white",font=('algerian',16,'bold'),bd=5)
l4.place(x=160,y=250)
e3=Entry(win,font=("algerian",16,"bold"),bg="white",fg="black",bd=5,width=25,show="*",textvariable=password)
e3.place(x=80,y=280)
c1=Checkbutton(win,text="all terms and condition are true",font=("algerian",10),bg="blue",fg="black",variable=cb,onvalue=1,offvalue=0,command=cbs)
c1.place(x=50,y=330)
b1=Button(win,text="LogIn",font=("algerian",10),bg="green",fg="white",bd=5,state="disabled",command=signin)
b1.place(x=60,y=380)
b2=Button(win,text="SingUp",font=("algerian",10),bg="green",fg="white",bd=5,command=signup)
b2.place(x=200,y=380)
b3=Button(win,text="Forgot Password",font=("algerian",10),bg="green",fg="white",bd=5,command=forgotpassword)
b3.place(x=340,y=380)
l5=Label(win,text="IGNTU_RCM,Makhan village,p.o-Awang sekmai,kangpokpi district,",font=("algerian",8),bg="blue",fg="white")
l5.place(x=40,y=450)
l6=Label(win,text="Manipur 795136,India.",font=("algerian",8),bg="blue",fg="white")
l6.place(x=60,y=465)
win.mainloop()
